project:
  type: book
  output-dir: docs/
  
freeze: auto  

execute:
  warning: false
  message: false
  cache: true


book:
  title: "Modern Probability Modeling"
  subtitle: "A Tools Approach"
  author: "Carlisle Rainey"
  google-analytics: "G-ZV1MJ9E632"
  chapters:
    - index.qmd
    - part: "Week 2"
      chapters:
      - wk02/01-maximum-likelihood.qmd
      - wk02/02-invariance-property.qmd
      - wk02/03-predictive-distribution.qmd
    - part: "Week 3"
      chapters: 
      - wk03/01-sampling-distribution.qmd
      - wk03/02-parametric-bootstrap.qmd
      - wk03/03-fisher-information-matrix.qmd
      - wk03/04-delta-method.qmd
      - wk03/05-evaluating-cis.qmd
    - part: "Week 4"
      chapters:
      - wk04/01-design-matrix.qmd
      - wk04/02-formulas.qmd
      - wk04/03-logistic-regression.qmd
      - wk04/04-big-four.qmd
    - part: "Week 5"
      chapters:
      - wk05/01-marginaleffects.qmd
      - wk05/02-ic.qmd
      - wk05/03-zero-inflation.qmd
  appendices:
    - appendicies/999-distributions.qmd
    - wk01/frac-exp-log.qmd
    - wk01/calculus-1.qmd
    - wk01/calculus-2.qmd
    - wk01/matrices.qmd
    - wk01/probability.qmd
    - wk04/05-glm.qmd
    #- wk01/hypothesis-testing.qmd

bibliography: references.bib

format:
  html:
    theme:
      - journal
      - brand
    css: _styles.css  
    citation-location: margin
    reference-location: margin




