{
  "hash": "e8ac57c624a82f0951229ebcd51484b5",
  "result": {
    "engine": "knitr",
    "markdown": "# Derivatives\n\n## Definition\n\nFirst derivatives describe the **rate of change** of a function.\n\n::: {#def-derivative}\nThe **derivative** of a function $f$ at a point $x$ is defined as $f'(x) = \\frac{df}{dx} = \\lim_{h \\to 0} \\frac{f(x + h) - f(x)}{h}$. If this limit exists, then $f$ is differentiable at $x$.\n:::\n\n::: {#exm-derivative1}\nLet $f(x) = x^2$. Use the definition to compute $f'(x)$.\n:::\n\n*Solution.* Use the definition of the derivative:\n$f'(x) = \\lim_{h \\to 0} \\frac{f(x + h) - f(x)}{h}$.\n\nWe have:\n- $f(x + h) = (x + h)^2 = x^2 + 2xh + h^2$\n- $f(x + h) - f(x) = x^2 + 2xh + h^2 - x^2 = 2xh + h^2$\n- $\\frac{f(x + h) - f(x)}{h} = \\frac{2xh + h^2}{h} = 2x + h$\n\nTaking the limit as $h \\to 0$, we get $f'(x) = \\lim_{h \\to 0} (2x + h) = 2x$.\n\n## Physical Interpretation of Derivatives\n\nSuppose you're driving a car, and you know how far you've traveled at every point in time. This distance is given by the function $f(x)$, where $x$ is time and $f(x)$ is the distance you've traveled (say, in meters). \n\nBut if I ask you *how fast you are going at a specific point*, that's a different question. You're no longer asking about distance. Instead, you're asking about *rate of change*.\n\nDerivatives help us learn about rate of change from a function describing distance traveled.\n\nThe derivative describes a quantity is changing at a given moment. If $f(x)$ is your position, then $f'(x)$ is your **velolcity**----how fast your position is changing. And $f''(x)$ is your **acceleration**---how fast your velocity is changing. This idea extends naturally to even higher-order changes, in the table below.\n\n| Order | Notation       | Name             | Interpretation                     | Units (if $x$ is time)       |\n|-------|----------------|------------------|------------------------------------|-------------------------------|\n| 0     | $f(x)$         | Position         | Where you are                      | Meters (m)                    |\n| 1     | $f'(x)$        | Velocity         | How fast you're moving             | Meters per second (m/s)       |\n| 2     | $f''(x)$       | Acceleration     | How fast your speed is changing    | Meters per second² (m/s²)     |\n| 3     | $f^{(3)}(x)$   | Jerk             | How fast your acceleration changes | Meters per second³ (m/s³)     |\n| 4     | $f^{(4)}(x)$   | Snap (Jounce)    | Rate of change of jerk             | Meters per second⁴ (m/s⁴)     |\n| 5     | $f^{(5)}(x)$   | Crackle          | Rarely used                        | Meters per second⁵ (m/s⁵)     |\n| 6     | $f^{(6)}(x)$   | Pop              | Even more rarely used              | Meters per second⁶ (m/s⁶)     |\n\nFor example, when you are taking off in a jet, you might have felt your head pressed harder and harder into your headrest. This is because $f^{(3)}(x)$ (i.e., \"jerk\") is positive. The jet is accelerating at an increasing rate, or the jet's speed is increasing at an increasing rate. In a car, jerk is generally what makes aggressive driving feel uncomfortable. Accelerating at a constant rate (i.e., jerk equals zero) to the desired speed and then maintaining that speed (i.e., again, jerk equals zero) feels comfortable.\n\nThe key idea is this: **derivatives measure how things change**. This concept is fundamental to both statistical theory and social science.\n\n---\n\n### Why this matters\n\nMany real-world questions are really about *change*:\n\n- **How fast is inflation rising?**\n- **At what point is profit maximized?**\n- **How steep is this hill at this point?**\n- **How quickly is a treatment effect decaying over time?**\n\nAll of these questions require derivatives. And to understand them, you need to develop a feel for what a derivative *is*. That’s what we’ll do next.\n\n\n## Rules for Derivatives\n\nThe rules below describe how differentiate common types of functions. Each rule can be derived from @def-derivative.\n\n### Constant Rule\n\n::: {#thm-const}\n## Constant Rule\nIf $f(x) = a$ (a constant), then $f'(x) = 0$.\n:::\n\n::: {#exm-deriv1}\nLet $f(x) = 5$. Compute $f'(x)$.\n:::\n\n*Solution.* The derivative of a constant is zero: $f'(x) = 0$. Remember that a derivative is a rate of change. A constant function is not changing, so it makes sense that the derivative is zero.\n\n---\n\n### Power Rule\n\n::: {#thm-power}\n## Power Rule\nIf $f(x) = x^n$, then $f'(x) = nx^{n-1}$.\n:::\n\n::: {.proof}\n\nThis proof assumes that $n$ is a positive integer. However, @thm-power holds for all real numbers.\n\nStart with definition of the derivative from @def-derivative $f'(x) = \\lim_{h \\to 0} \\frac{f(x + h) - f(x)}{h}$.\n\nLet $f(x) = x^n$. Then $f'(x) = \\lim_{h \\to 0} \\frac{(x + h)^n - x^n}{h}$\n\nExpand $(x + h)^n$ using the binomial theorem so that \n\n$$\n(x + h)^n = \\sum_{k = 0}^n \\binom{n}{k} x^{n - k} h^k = x^n + \\binom{n}{1} x^{n - 1} h + \\binom{n}{2} x^{n - 2} h^2 + \\cdots + h^n.\n$$\n\nSubtract $x^n$ so that\n\n$$\n(x + h)^n - x^n = \\binom{n}{1} x^{n - 1} h + \\binom{n}{2} x^{n - 2} h^2 + \\cdots + h^n.\n$$\n\nDivide by $h$ so that \n\n$$\n\\frac{(x + h)^n - x^n}{h} = \\binom{n}{1} x^{n - 1} + \\binom{n}{2} x^{n - 2} h + \\cdots + h^{n - 1}.\n$$\n\nTake the limit as $h \\to 0$ so that\n\n$$\nf'(x) = \\lim_{h \\to 0} \\left[\\binom{n}{1} x^{n - 1} + \\binom{n}{2} x^{n - 2} h + \\cdots + h^{n - 1} \\right] = \\binom{n}{1} x^{n - 1} = n x^{n - 1}\n$$\n:::\n\n\n\n\n::: {#exm-deriv2a}\nLet $f(x) = x^3$. Compute $f'(x)$.\n:::\n\n*Solution.* Using the power rule $f'(x) = 3x^2$.\n\n::: {#exm-deriv2b}\nLet $f(x) = x^5 - 2x^2 + 7$. Compute $f'(x)$.\n:::\n\n*Solution.* Notice that this function is a sum of three functions. Differentiate each term using the power rule, giving $f'(x) = 5x^4 - 4x + 0 = 5x^4 - 4x$. \n\n---\n\n### Exponential Rule\n\n::: {#thm-exp}\n## Exponential Rule\nIf $f(x) = e^x$, then $f'(x) = e^x$.\n:::\n\n\n### Logarithm Rule\n\n::: {#thm-log}\n## Logarithm Rule\nIf $f(x) = \\log(x)$, then $f'(x) = \\frac{1}{x}$ for $x > 0$.\n:::\n\n### Sum Rule\n\n::: {#thm-sum}\n## Sum Rule\nIf $f(x) = g(x) + h(x)$, then $f'(x) = g'(x) + h'(x)$.\n:::\n\n::: {#exm-deriv3}\nLet $f(x) = x^2 + \\log(x)$. Compute $f'(x)$.\n:::\n\n*Solution.* Differentiate each term so that $f'(x) = 2x + \\frac{1}{x}$.\n\n### Product Rule\n\n::: {#thm-product}\n## Product Rule\nIf $f(x) = g(x) h(x)$, then $f'(x) = g'(x) h(x) + g(x) h'(x)$.\n:::\n\n::: {#exm-deriv4}\nLet $f(x) = x^2 \\cdot \\log(x)$. Compute $f'(x)$.\n:::\n\n*Solution.* Let $g(x) = x^2$ and $h(x) = \\log(x)$. Then $g'(x) = 2x$ and $h'(x) = \\frac{1}{x}$. Apply the product rule so that \n\n$$\nf'(x) = 2x \\cdot \\log(x) + x^2 \\cdot \\frac{1}{x} = 2x \\log(x) + x.\n$$\n\n### Quotient Rule\n\n::: {#thm-quotient}\n## Quotient Rule\nIf $f(x) = \\frac{g(x)}{h(x)}$, then $f'(x) = \\frac{g'(x) h(x) - g(x) h'(x)}{[h(x)]^2}$.\n:::\n\n::: {#exm-deriv5}\nLet $f(x) = \\frac{\\log(x)}{x^2}$. Compute $f'(x)$.\n:::\n\n*Solution.* Let $g(x) = \\log(x)$ and $h(x) = x^2$. Then $g'(x) = \\frac{1}{x}$ and $h'(x) = 2x$. Apply the quotient rule so that\n\n$$\nf'(x) = \\frac{(1/x) \\cdot x^2 - \\log(x) \\cdot 2x}{x^4} = \\frac{x - 2x \\log(x)}{x^4} = \\frac{1 - 2 \\log(x)}{x^3}.\n$$\n\n### Chain Rule\n\nThe chain rule is really important! We can think of many functions $f$ as a function of a function. In this case, This allows us to use the rules above, which apply to relatively simple functions, to much more complicated function.\n\n::: {#thm-chain}\n## Chain Rule\nIf $f(x) = h(g(x))$, then $f'(x) = h'(g(x)) \\cdot g'(x)$.\n:::\n\n::: {#exm-deriv6}\nLet $f(x) = \\log(x^2 + 1)$. Compute $f'(x)$.\n:::\n\n*Solution.* We have $f(x) = \\log(x^2 + 1)$ (complicated!). But let $g(x) = x^2 + 1$ (simple!) and $h(u) = \\log(u)$ (simple!). Then $g'(x) = 2x$ and $h'(u) = \\frac{1}{u}$. Then $f'(x) = \\frac{1}{x^2 + 1} \\cdot 2x = \\frac{2x}{x^2 + 1}$.\n\n::: {#exm-deriv6b}\nLet $f(x) = \\exp(x^2 + 3x)$. Compute $f'(x)$.\n:::\n\n*Solution.* We have $f(x) = \\exp(x^2 + 3x)$ (complicated!). But let $g(x) = x^2 + 3x$ (simple!) and $h(u) = \\exp(u)$ (simple!). Then $g'(x) = 2x + 3$ and $h'(u) = \\exp(u)$. So $f'(x) = \\exp(x^2 + 3x) \\cdot (2x + 3)$.\n\n::: {#exm-deriv6c}\nLet $f(x) = x^2 \\cdot \\exp(x^2)$. Compute $f'(x)$.\n:::\n\n*Solution.* We have $f(x) = x^2 \\cdot \\exp(x^2)$. We can use the product rule. Breaking it into pieces, we have $g(x) = x^2$ (simple!) and $h(x) = \\exp(x^2)$ (we can handle this with the chain rule). \n\nApply the **product rule**: \n\n- $g'(x) = 2x$\n- To differentiate $h(x) = \\exp(x^2)$, use the chain rule. Let $u(x) = x^2$ and $h(u) = \\exp(u)$, so $h'(x) = \\exp(x^2) \\cdot 2x$.\n\n$$\nf'(x) = g'(x) \\cdot h(x) + g(x) \\cdot h'(x) = 2x \\cdot \\exp(x^2) + x^2 \\cdot (2x \\cdot \\exp(x^2)) = 2x \\exp(x^2) + 2x^3 \\exp(x^2)\n$$\n\nYou could factor if you wanted: $f'(x) = 2x \\exp(x^2)(1 + x^2)$.\n\n\n## Mixed Examples\n\nThese examples require two or more rules.\n\n::: {#exm-mixed1}\nLet $f(x) = x^2 \\cdot \\log(x^2 + 1)$. Compute $f'(x)$.\n:::\n\n*Solution.* This is a **product** of $x^2$ and $\\log(x^2 + 1)$.\n\nLet $g(x) = x^2$ and $h(x) = \\log(x^2 + 1)$.\n\n- $g'(x) = 2x$\n- $h'(x) = \\frac{1}{x^2 + 1} \\cdot 2x = \\frac{2x}{x^2 + 1}$ by the chain rule\n\nApply the product rule:\n\n$f'(x) = 2x \\cdot \\log(x^2 + 1) + x^2 \\cdot \\frac{2x}{x^2 + 1}$\n\nSimplify: $f'(x) = 2x \\log(x^2 + 1) + \\frac{2x^3}{x^2 + 1}$\n\n\n::: {#exm-mixed2}\nLet $f(x) = \\frac{x^2}{\\log(x)}$. Compute $f'(x)$.\n:::\n\n*Solution.* This is a **quotient** with $g(x) = x^2$, $g'(x) = 2x$, $h(x) = \\log(x)$, $h'(x) = \\frac{1}{x}$.\n\nApply the quotient rule:\n\n$f'(x) = \\frac{2x \\cdot \\log(x) - x^2 \\cdot \\frac{1}{x}}{(\\log(x))^2}$\n\nSimplify numerator: $2x \\log(x) - x$\n\nFinal result: $f'(x) = \\frac{2x \\log(x) - x}{(\\log(x))^2}$\n\n::: {#exm-mixed3}\nLet $f(x) = \\log(e^{x^2})$. Compute $f'(x)$.\n:::\n\n*Solution.* Use the identity $\\log(e^u) = u$:\n\nSo $f(x) = x^2$, and $f'(x) = 2x$.\n\nAlternatively, apply the chain rule directly:\n\nLet $g(x) = e^{x^2}$, so $g'(x) = e^{x^2} \\cdot 2x$\n\nThen $f(x) = \\log(g(x))$, so $f'(x) = \\frac{1}{g(x)} \\cdot g'(x) = \\frac{1}{e^{x^2}} \\cdot (e^{x^2} \\cdot 2x) = 2x$\n\n::: {#exm-mixed4}\nLet $f(x) = \\exp(x) \\cdot \\log(x^2 + 1)$. Compute $f'(x)$.\n:::\n\n*Solution.* This is a **product** rule with a **chain** inside.\n\nLet $g(x) = \\exp(x)$, $g'(x) = \\exp(x)$\n\nLet $h(x) = \\log(x^2 + 1)$, $h'(x) = \\frac{2x}{x^2 + 1}$\n\nApply product rule:\n\n$f'(x) = \\exp(x) \\cdot \\log(x^2 + 1) + \\exp(x) \\cdot \\frac{2x}{x^2 + 1}$\n\n::: {#exm-mixed5}\nLet $f(x) = \\frac{x^3 \\cdot \\log(x)}{e^x}$. Compute $f'(x)$.\n:::\n\n*Solution.* This is a **quotient** with a **product in the numerator**.\n\nLet numerator $u(x) = x^3 \\cdot \\log(x)$ and denominator $v(x) = e^x$\n\n- $u'(x) = 3x^2 \\cdot \\log(x) + x^3 \\cdot \\frac{1}{x} = 3x^2 \\log(x) + x^2$\n- $v'(x) = e^x$\n\nApply the quotient rule:\n\n$f'(x) = \\frac{u'(x) \\cdot v(x) - u(x) \\cdot v'(x)}{(e^x)^2}$\n\nSubstitute:\n$f'(x) = \\frac{[3x^2 \\log(x) + x^2] \\cdot e^x - x^3 \\log(x) \\cdot e^x}{e^{2x}}$\n\nFactor $e^x$ in the numerator:\n$f'(x) = \\frac{e^x \\cdot [3x^2 \\log(x) + x^2 - x^3 \\log(x)]}{e^{2x}} = \\frac{3x^2 \\log(x) + x^2 - x^3 \\log(x)}{e^x}$\n\n## Higher-Order Derivatives\n\nOnce we compute the first derivative $f'(x)$, we can keep differentiating.\n\n- The **second derivative** measures how the rate of change itself is changing — that is, the **curvature** of the function.\n- The **third derivative** measures how the curvature is changing.\n- This process can continue as long as the function is smooth enough.\n\n### Notation\n\n- $f'(x) = \\frac{df}{dx}$: first derivative\n- $f''(x) = \\frac{d^2f}{dx^2}$: second derivative\n- $f^{(3)}(x) = \\frac{d^3f}{dx^3}$: third derivative\n- In general, $f^{(n)}(x)$ is the $n$th derivative of $f$\n\n### Examples\n\n::: {#exm-second1}\nLet $f(x) = x^3$. Compute the second and third derivatives.\n:::\n\n*Solution.* First derivative: $f'(x) = 3x^2$  \nSecond derivative: $f''(x) = 6x$  \nThird derivative: $f^{(3)}(x) = 6$\n\nSo $f^{(n)}(x) = 0$ for all $n \\ge 4$.\n\n---\n\n::: {#exm-second2}\nLet $f(x) = x^2 \\log(x)$. Compute the second derivative.\n:::\n\n*Solution.*  \nWe already computed the first derivative:\n\n$f'(x) = 2x \\log(x) + x$\n\nDifferentiate again:\n\n- First term: $d/dx[2x \\log(x)] = 2 \\log(x) + 2$\n- Second term: $d/dx[x] = 1$\n\nSo $f''(x) = 2 \\log(x) + 2 + 1 = 2 \\log(x) + 3$\n\n---\n\nHigher-order derivatives are especially useful in:\n\n- Optimization: Second derivatives help determine concavity and maxima/minima.\n- Taylor approximations: Higher-order derivatives appear in polynomial expansions.\n- Differential equations and modeling: Many physical laws involve second or third derivatives.\n\n\n## Derivatives for Multivariable Functions\n\nFor functions of more than one variable, we still talk about rates of change — but now we consider how the function changes in **each direction**.\n\nLet $f(x_1, x_2, \\dots, x_n)$ be a function of $n$ variables.\n\n### Gradient\n\nThe **gradient** is the multivariable generalization of the first derivative. It tells us how $f$ changes with respect to each input variable.\n\n::: {#def-gradient}\nThe **gradient** of $f$ is the vector of partial derivatives:\n\n$$\n\\nabla f(x) = \\left[\n\\frac{\\partial f}{\\partial x_1},\\ \n\\frac{\\partial f}{\\partial x_2},\\ \n\\cdots,\\ \n\\frac{\\partial f}{\\partial x_n}\n\\right]\n$$\n\nIt points in the direction of steepest ascent.\n:::\n\n#### Example\n\nLet $f(x, y) = x^2 + 3y$. Then:\n\n$$\n\\nabla f(x, y) = \\left[ \\frac{\\partial f}{\\partial x}, \\frac{\\partial f}{\\partial y} \\right] = [2x,\\ 3]\n$$\n\nAt the point $(1, 2)$, the gradient is $[2,\\ 3]$.\n\n---\n\n### Hessian\n\nThe **Hessian** is the multivariable generalization of the second derivative. It contains all second partial derivatives and describes the **curvature** of the function.\n\n::: {#def-hessian}\nThe **Hessian matrix** of $f$ is the $n \\times n$ matrix of second-order partial derivatives:\n\n$$\nH_f(x) =\n\\begin{bmatrix}\n\\frac{\\partial^2 f}{\\partial x_1^2} & \\frac{\\partial^2 f}{\\partial x_1 \\partial x_2} & \\cdots \\\\\n\\frac{\\partial^2 f}{\\partial x_2 \\partial x_1} & \\frac{\\partial^2 f}{\\partial x_2^2} & \\cdots \\\\\n\\vdots & \\vdots & \\ddots\n\\end{bmatrix}\n$$\n:::\n\n- The diagonal entries describe curvature in each direction.\n- The off-diagonal entries describe how changes in one variable affect curvature in another.\n\n#### Example\n\nLet $f(x, y) = x^2 y + y^3$. Then:\n\n- $\\frac{\\partial^2 f}{\\partial x^2} = 2y$\n- $\\frac{\\partial^2 f}{\\partial y^2} = 6y$\n- $\\frac{\\partial^2 f}{\\partial x \\partial y} = \\frac{\\partial^2 f}{\\partial y \\partial x} = 2x$\n\nSo the Hessian is:\n\n$$\nH_f(x, y) =\n\\begin{bmatrix}\n2y & 2x \\\\\n2x & 6y\n\\end{bmatrix}\n$$\n\n---\n\nThese ideas are especially important in:\n\n- **Optimization**: Gradient = direction to move; Hessian = curvature (convexity/concavity)\n- **Statistical modeling**: Maximum likelihood estimation uses gradients (score functions) and Hessians (information matrices)\n- **Machine learning**: Gradients are used in backpropagation and optimization algorithms.\n\n\n## Symbolic Differentiation in R\n\nYou can compute derivatives symbolically in R using the `D()` function.\n\nThe basic syntax is:\n\n```r\nD(expression, \"variable\")\n```\n\nThis returns the symbolic derivative of an expression with respect to the named variable.\n\n::: {#exm-rsymbolic1}\nDifferentiate $x^2$.\n:::\n\n*Solution.* Use `D()` with a formula input:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nD(expression(x^2), \"x\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2 * x\n```\n\n\n:::\n:::\n\n\n\n\nThis returns:\n\n```\n2 * x\n```\n\n::: {#exm-rsymbolic2}\nDifferentiate $x^2 \\log(x)$ using the product rule.\n:::\n\n*Solution.* R handles this automatically:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nD(expression(x^2 * log(x)), \"x\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2 * x * log(x) + x^2 * (1/x)\n```\n\n\n:::\n:::\n\n\n\n\nReturns:\n\n```\n2 * x * log(x) + x\n```\n\nThis matches the product rule: $f'(x) = 2x \\log(x) + x$.\n\n::: {#exm-rsymbolic3}\nDifferentiate $\\frac{x^3}{\\exp(x)}$.\n:::\n\n*Solution.* R will apply the quotient rule:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nD(expression(x^3 / exp(x)), \"x\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3 * x^2/exp(x) - x^3 * exp(x)/exp(x)^2\n```\n\n\n:::\n:::\n\n\n\n\nReturns:\n\n```\n((3 * x^2 * exp(x)) - (x^3 * exp(x))) / exp(x)^2\n```\n\nThis simplifies to the same expression obtained manually.\n\n---\n\nTo simplify or evaluate expressions numerically, you can use `deriv()`, `eval()`, or symbolic math tools in packages like **Ryacas**, **caracas**, or **symengine**.\n\n## Numeric Differentiation in R\n\nWhen symbolic derivatives are unavailable, R can approximate first derivatives numerically using finite differences. The `numDeriv` package provides convenient tools.\n\nInstall the package if needed:\n\nThen load it:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(numDeriv)\n```\n:::\n\n\n\n\n### First Derivative\n\nUse `grad()` to compute the approximate derivative of a single-variable function at a point.\n\n::: {#exm-rnumeric1}\nLet $f(x) = x^2 \\log(x)$. Compute $f'(2)$ numerically.\n:::\n\n*Solution.* Define the function and apply `grad()`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nf <- function(x) x^2 * log(x)\ngrad(f, x = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.772589\n```\n\n\n:::\n:::\n\n\n\n\nReturns:\n\n```\n[1] 4.772589\n```\n\nThis matches the exact result: $f'(x) = 2x \\log(x) + x$, so $f'(2) = 4 \\log(2) + 2 \\approx 4.7726$.\n\n---\n\nNumeric differentiation is useful when working with functions that are not easily expressed in closed form.\n\n## Comparing Derivatives: By Hand, Symbolic, and Numeric\n\nAll three approaches — manual rules, symbolic differentiation, and numeric approximation — should yield consistent results.\n\n::: {#exm-compare1}\nLet $f(x) = x^2 \\log(x)$. Compute $f'(2)$:\n- by hand using rules,\n- symbolically using `D()`,\n- numerically using `grad()`.\n:::\n\n*Solution.*\n\n### By Hand\n\nUse the product rule: $f(x) = x^2 \\cdot \\log(x)$\n\n- $f'(x) = 2x \\log(x) + x$\n- So $f'(2) = 4 \\log(2) + 2 \\approx 4.7726$\n\n### Symbolic in R\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nD(expression(x^2 * log(x)), \"x\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2 * x * log(x) + x^2 * (1/x)\n```\n\n\n:::\n:::\n\n\n\n\nReturns:\n\n```\n2 * x * log(x) + x\n```\n\nSame expression as the hand-calculated result.\n\nTo evaluate at $x = 2$:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\neval(D(expression(x^2 * log(x)), \"x\"), list(x = 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.772589\n```\n\n\n:::\n:::\n\n\n\n\nReturns:\n\n```\n[1] 4.772589\n```\n\n### Numeric in R\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(numDeriv)\nf <- function(x) x^2 * log(x)\ngrad(f, x = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.772589\n```\n\n\n:::\n:::\n\n\n\n\nReturns:\n\n```\n[1] 4.772589\n```\n\n### Conclusion\n\nAll three methods give the same result:  \n$f'(2) = 4.772589$, verifying the equivalence of symbolic, numeric, and manual differentiation.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}